### ISSUE TITLE
[bug] connection is still open after saving the models

### ISSUE THREAD

**Issue by TBD** [VladTM23/MongoModels#1]
**problem:**
* Dupa ce apelez "node index.js", nu stium cum sa ma exprim, dar "it still hangs", adica in terminal nu reapare prompt-ul, insa in baza de date se adauga corect si functioneaza. 

**hints:**
* https://mongoosejs.com/docs/api/connection.html#connection_Connection-close
* https://mongoosejs.com/docs/api/model.html#model_Model-save
* add a console.log(...) after save methods

**Comment by VladTM23** [comment]
Fixed. 

mongoose.connection.close() is a whimsy function. :)
